version: "2.0"
services:
  shopbackend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: shopbackend
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/shopdbdata:/var/lib/mysql
    ports:
      - 3306:3306
